[package]
name = "skim-pinyin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "*"
pinyin = "0.9"
clap = { version = "4.2.7", features = ["derive"] }
